sudo: required
services:
  - docker

before_install:
  - docker build -t rickcruzz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rickcruzz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-central-1-306476627547"
  bucket_path: "docker"
  on:
    branch: master